### ISSUE TITLE
AES-128-CBC and AES-256-CBC with the correct key lengths

### ISSUE THREAD

**Issue by idan003** [rap2hpoutre/laravel-log-viewer#164]
Hi, i have issue with larvel log, i install everything and put everything in the config app file.
but when i try to go website.com/logs he tell me that:
The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths.

im use Lumen (5.6.4) (Laravel Components 5.6.*)

tnx

**Comment by elminson** [comment]
Please follow this 
`php artisan key:generate`
`php artisan config:cache`
https://github.com/laravel/framework/issues/9080

**Comment by elminson** [comment]
@idan003 any update with this?

**Comment by rap2hpoutre** [comment]
@idan003 Since it's a problem with lumen, the solution given by @elminson could not work, (still the analysis is good, thank you so much @elminson: you are right, it's about app key) so maybe you could have a look at https://stackoverflow.com/questions/30344141/lumen-micro-framework-php-artisan-keygenerate.

**Comment by elminson** [comment]
Yes @rap2hpoutre, Lumen doesn't have the command, so needs to add an app key to .env,
to generate one you can use one of these:
```
date | md5
date | md5sum
openssl rand -base64 24
php -r "echo password_hash(uniqid(), PASSWORD_BCRYPT).\"\n\";"
```
You can close this issue :)

**Comment by rap2hpoutre** [comment]
@idan003 I close this issue. Let me now if there is anything else!
