### ISSUE TITLE
How to change Time format

### ISSUE THREAD

**Issue by YogSharma** [rap2hpoutre/laravel-log-viewer#182]
change time format according to need while showing logs.

**Comment by rap2hpoutre** [comment]
There is no way to change the date format via Log viewer, because the log viewer just reads the log files and displays it. So you will have to configure it in the log **writer** which is provided by Laravel. See https://stackoverflow.com/questions/52117102/laravel-customize-log-formatter and https://laravel.com/docs/5.7/logging#advanced-monolog-channel-customization
