### ISSUE TITLE
Do you want a remove button?

### ISSUE THREAD

**Issue by iwasherefirst2** [rap2hpoutre/laravel-log-viewer#207]
Hi,

I usually check my log file for bugs and remove then when I have fixed them. I finf it convenient to have an option to delete a single entry from log file by pressing a button:

![image](https://user-images.githubusercontent.com/1765602/65453029-a50fe180-de42-11e9-8a11-d207a4dae4b2.png)

Is that in the scope of the package? If so I could send a PR

**Comment by hulkur** [comment]
This could result in locking problem when app wants to write while you delete a row in same log file

**Comment by rap2hpoutre** [comment]
Hi @iwasherefirst2 (nice username BTW!). Sorry for super late answer. I think this could be had to develop since this package parses strings in files. Also, I see two issue that could happen. The first one is the one mentioned by @hulkur (thank you for pointing this). The second one is that it could be dangerous where you suggested to add it: I want to expand a log and OOPS I clicked on delete. I recommend using a more advanced log system and log viewer if you need to "archive" log entries.

**Comment by iwasherefirst2** [comment]
@rap2hpoutre I actually already developed and use it for myself, it boils down to a simple regex search. 

For the locking problem: the `Storage` method does not use flock by default, but one can pass a parameter to do so, buts one would need to make the change in the logger class, which is outside the package. SO okay, I get why we should not implement the feature. 

For the OOPS problem: I think it would be no problem to save every deleted row in a backup file.
