### ISSUE TITLE
Allow downloading zip versions of large files

### ISSUE THREAD

**Issue by shamakhan** [rap2hpoutre/laravel-log-viewer#208]
If the file size is larger than 50 MB, so can you give an option to download its zip rather than the whole file?

**Comment by rap2hpoutre** [comment]
Hi, thank you for your contribution! Zipping file server-side will consume memory and time (and require writing rights on some directories) so I think it could introduce new issues (memory limit, etc.). You will still have to unzip it when you receive it, so I'm not sure it will help preserving storage space. Since I want to keep this library light and simple (without too much dependencies), I think this need will not fit. What is your actual problem with file size?
