### ISSUE TITLE
Request: Dark Mode viewer

### ISSUE THREAD

**Issue by timothymarois** [rap2hpoutre/laravel-log-viewer#213]
Possibility to **add dark mode to the viewer**? 

I know this is a low priority, but as I work in a lot of dark mode management systems, it would be great to have a dark version of the error logs. Seems like it would be a simple option in the config to allow dark mode and quick CSS modifications.

and thanks for everyone who has worked on this project thus far, I was planning to do something for one of my projects and came across this, saved me a lot of time.

**Comment by codevio** [comment]
@rap2hpoutre Can we merge #140 so I will take this new design to add dark mode ?

**Comment by codevio** [comment]
@rap2hpoutre ?

**Comment by rap2hpoutre** [comment]
Hi @timothymarois and @codevio thank you for your patience and sorry for super late answer. @codevio The PR has been closed by its creator. You could create a dark mode for the current design (but maybe you have not enough time now since I did not answer). I'm really sorry about the delay and hope your eyes are safe 😅

**Comment by timothymarois** [comment]
@rap2hpoutre Thanks, yeah time is limited, but I use the logs often, I might look into this eventually if no one else does.

**Comment by timothymarois** [comment]
@rap2hpoutre I decided to add simple dark mode to get this moving along. #233

**Comment by rap2hpoutre** [comment]
Available in v1.6.0 thanks to @timothymarois ! 🎉
