### ISSUE TITLE
Live Stream Log

### ISSUE THREAD

**Issue by CWSpear** [rap2hpoutre/laravel-log-viewer#26]
It would be awesome if the page would automatically update when there are new items to show.

Ideally, this would be done with sockets. I don't have a lot of experience with sockets in PHP, but I've found it's not nearly as easy as say, Node and `socket.io`.

I'm really not sure how viable this is in pure PHP (i.e. I don't know that you can really watch for file changes in realtime with PHP), but it would be a super useful feature! Definitely possible and not terrible difficult with Node, but that'd require another dependency.

Just wanted to throw this out there and see if anyone else had any ideas.

**Comment by CWSpear** [comment]
In my research, I found [jasonlewis/resource-watcher](https://github.com/jasonlewis/resource-watcher), which just polls every second.

**Comment by RobinHoutevelts** [comment]
Only PHP CLI is suited for long-running apps.
It's even mentioned on  [jasonlewis/resource-watcher](https://github.com/jasonlewis/resource-watcher)

> Resource Watcher is best used from a console.

However, you could write something in javascript that polls the controller which checks the log and returns the new lines.
Then back on the client-side you would append this to the page.

On the PHP's side it's fairly little work.
Something like this https://gist.github.com/RobinHoutevelts/1f143d4554dc210dedd0 might already do the trick ( sorry for the code style ).

The difficult part would be to append it into the DataTable on the javascript-side.
I guess you could just insert the logs into the table and re-run the `$('#table-log').DataTable` call.

**Comment by CWSpear** [comment]
There's always https://github.com/reactphp/react!

But again, maybe extra work (and work to set up just to get logs running for the end user!)

When you say DataTable, do you mean https://www.datatables.net/?

**Comment by rap2hpoutre** [comment]
Thanks for your suggestions :)

> When you say DataTable, do you mean https://www.datatables.net/?

Yes.

About "Live Stream Log": 
I think auto update is risky: what if I'm on second (or third, etc.) page when it's update ? Or what if I doing a search or a filter on the result table ? It could be annoying if the page content is changing while I'm browsing or reading. Maybe just a notification (something like [this](http://getbootstrap.com/components/#badges) in left menu) ?

**Comment by RobinHoutevelts** [comment]
> what if I'm on second (or third, etc.) page when it's update ? Or what if I doing a search or a filter on the result table ?

If you inject the log-rows directly into the DataTables object this won't be an issue. 

	var dataTable = $('#table-log').DataTable();
	dataTable.fnAddData([col1,col2, col3, ..]);

The "difficult" part I was talking about is maintaining the layout.
for example: `<td class="text-{{{$log['level_class']}}}">`

To accomplish this you'll have to use the `createdRow` option.

I've created a [JSbin](http://live.datatables.net/jaluxehu/7/edit) that shows nearly all the work.
As you can see the rows are dynamically added from the `data` variable AND the `td`-elements are manually updated.


I'm swamped with work right now but I'll see if I can find the time to create a pull request.

**Comment by CWSpear** [comment]
There are a lot of different places you could approach this from a UX perspective: You could remove paging and you could have a `tail -f` like experience, where it just loads the last ~10 items (and you could load more) and then if you're scrolled to the bottom, it adds more items to the bottom as they're automatically added (and it keeps "scrolled to bottom"). Then if they are not scrolled to the bottom, it just maintains they're position (and you could have notifications, or badges, etc).

Or maybe it's a checkbox to "stick to bottom." etc, etc.

But yeah, that'd be extreme. But there's lots of different ways you *could* solve it if you felt like you really wanted to embrace this feature.

**Comment by RobinHoutevelts** [comment]
That's hell if you want to keep the filter- and search options.
You'll need to re-query the server every time you filter or search because you don't have everything loaded on the client side.

I fixed this by keeping count of how many rows I'm already showing. Every 2.5s I query the server and *tell* it how many rows (`n`) I already have.

The server then responds like usual but cuts of the first `n` rows leaving us with the *new* rows.

**Comment by CWSpear** [comment]
No, I think you could still keep the filter/search options just client-side. In fact, it's *very* rare that I want to search the backlog. I mean, this is how the `Clear Display` button (another feature that could be nice!) works in Mac's Console.app. If it's not visible, it's not searched/filtered.

I guess we're maybe considering two different kinds of use-cases: the one where there's an error in production and you want to take a look at what happened, and the other where you're developing, and you want to see all logging (as some may be debug output) as it's happening, and be able to clear the display as to make it obvious that "these messages happened since I last cleared," etc.

**Comment by RobinHoutevelts** [comment]
> In fact, it's *very* rare that I want to search the backlog.

In my case the search-option would be used to see how often an event occurred. Having all the logs available is necessary.

> No, I think you could still keep the filter/search options just client-side. ... **If it's not visible, it's not searched/filtered.**

That would nullify the reason I'm implementing this into my project.

> I guess we're maybe considering two different kinds of use-cases

I agree.
I'm currently implementing `laravel-log-viewer` so the lone sysadmin can lookup issues mentioned by the staff.
While I'm developing I just have the log file open in my IDE and clear it myself from time to time.

IMO the goal of this package should be to make it easier for **non-developers** to view the log-file.

> `Clear Display` button (another feature that could be nice!)

:+1:  I agree that this could be a useful feature, and one that *somewhat* merges the two use-cases together.

When you are developing you could have the page open, press `Clear Display` to remove the old logs from the screen.
Then with this live stream log feature you would only be seeing the new lines being added in real-time.

&nbsp;

Would this work for you?

**Comment by CWSpear** [comment]
:+1: I think that sounds good! =)

**Comment by rap2hpoutre** [comment]
**About "Live Stream"**, after thinking, I think I will not add this feature in Laravel Log Viewer for many reasons. Hope you will understand. Laravel Log Viewer must be kept *simple*, *light*, *easy to install*, to *extends*, and to *understand*. I don't want to add too much complexity. 

First question about this suggestion is "why?". It's fun (that's why I first wanted to accept it !). But who will keep an eye on a log waiting for new log ? (not me) It's a *log viewer*, not a *notifier*. I think if you need to be notified about new log warning, you should use slack notifications (https://github.com/maknz/slack) or something else, not check every five minutes a log reader ("is there any new log info ?"); It's rather for searching an info or check once a day, not for wait for new errors.

One other argument (maybe the most important) is about performance in parsing log data (my bad). It's really slow (too many regular expression, etc.). Some users (see https://github.com/rap2hpoutre/laravel-log-viewer/issues/10) have huge logs, or sometimes just big logs (a few MB). Parsing same log every 2 or 3 seconds can be catastrophic on production server, if someone keeps a tab open on its browser. This 2 or 3 seconds are not configurable, it's dangerous (and I don't want to add config options (complexity for users once again)) 

Some people (https://github.com/rap2hpoutre/laravel-log-viewer/issues/9) extends views. If we add to many JS code in view(about 50 in PR https://github.com/rap2hpoutre/laravel-log-viewer/pull/28), it will be harder to understand and extend. And there is some duplication between JS and HTML, so it will be harder to maintain too.

I really (really) appreciate your contribution effort :beers:, it was very interesting :), but I think I will close this ticket (if you are OK)

**Comment by RobinHoutevelts** [comment]
> One other argument (maybe the most important) is about performance in parsing log data (my bad).

No worries, that's a decent argument!
Having to parse all logs also *feels wrong* to me but I didn't feel like rewriting the internals just for this modification.

> but I think I will close this ticket (if you are OK)

Go ahead. I'll just update our `composer.json` to use my fork then :+1:
