### ISSUE TITLE
Customizing views

### ISSUE THREAD

**Issue by billionsales** [rap2hpoutre/laravel-log-viewer#9]
Hello, good morning.

After trying a few different methods I found a way to make the package use my own View, adding this to routes.php in Laravel 4.2

\View::addNamespace('laravel-log-viewer', app_path().'/views/packages/laravel-log-viewer/');

I think it should be appropriate to add this information to Readme, I don't dare because I'm not sure this is the 100% best method.

Thanks.

**Comment by rap2hpoutre** [comment]
Hi !

Thanks !
I saw @AnthonyPorthouse made a fork to add overridable views : https://github.com/AnthonyPorthouse/laravel-log-viewer/commit/b92876c47fc17bc32325fbca73cc0c1abbc90ad4
I hope he will do a pull request :) because I think it will help you to customize view.

I don't know if you method will work with laravel 5 so I will wait before adding this to readme.

**Comment by AnthonyPorthouse** [comment]
Hey,

In my fork the code was added to the service provider to allow overriding the view in Laravel 5, however to make it also backwards compatible with 4.2 it would probably need some work such as method_exists checks.

**Comment by billionsales** [comment]
didn't knew, thanks!

**Comment by rap2hpoutre** [comment]
Ok, merged. I will create a release with this PR (now it's only on master) after some tests (@billionsales you can test too, if you want, it should work for you)

**Comment by rap2hpoutre** [comment]
Release created, you can update to v0.2.0 now

**Comment by billionsales** [comment]
Confirmed, working in 4.2, out of the box, thx.

**Comment by barryvanveen** [comment]
Notice that Laravel (I'm running 4.2) has a build-in way to override package views. You can place your custom view in /app/views/packages/ap2hpoutre/laravel-log-viewer and it will automatically be used instead of the view in /vendor/ap2hpoutre/laravel-log-viewer/src/views.

This only worked for me when the views were placed in there default folder, so /app/views for L4.2. My views were moved to /resources/views and that didn't work out.
